Repository MinThaMie/graph_isomorphism, pull requests merged in 2018-03, with the labels that each got.

#14 Use coloring class in Claudia’s alg.
  coloring_claudia.py
  coloring_dorien.py
  test_claudia/integration_test/test_coloring_claudia.py
  test_claudia/unittest/coloring_claudia_test.py
Labels: WIP

#25 Fix test environment
  .idea/runConfigurations/Run_all_tests.xml
  .travis.yaml
  tests/__init__.py
  tests/integration/__init__.py
  tests/integration/test_coloring_claudia.py
  tests/unit/__init__.py
  tests/unit/coloring_claudia_test.py
  tests/unit/test_color_refinement_dorien.py
  tests/unit/test_count_isomorphism_dorien.py
Labels: enhancement

#27 Fix test CI
  .idea/graph_isomorphism.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations/Run_all_tests.xml
  .idea/vcs.xml
  .travis.yml
  tests/integration/test_coloring_claudia.py
  tests/unit/test_color_refinement_dorien.py
  tests/unit/test_count_isomorphism_dorien.py
Labels: enhancement

#26 Preprocessing
  color_refiment_helper.py
  dll.py
  preprocessing/__init__.py
Labels: WIP, enhancement

#33 Improve graph.py and test environment
  .idea/runConfigurations/Run_all_tests_in_IDE.xml
  .idea/runConfigurations/Run_all_tests_in_shell.xml
  .travis.yml
  color_refiment_helper.py
  color_refinement.py
  graph.py
  graph_io.py
  tests/__init__.py
  tests/unit/test_coloring_claudia.py
  tests/unit/test_graph.py
  tests/unit/test_tools.py
  tools/__init__.py
Labels: enhancement

#40 Preprocess added to refinement and tests
  .gitignore
  .idea/modules.xml
  color_refinement.py
  preprocessing/__init__.py
  tests/__init__.py
  tests/integration/test_coloring_claudia.py
  tests/unit/test_preprocessing.py
Labels: enhancement

#39 Add graph complement method
  graph.py
  tests/__init__.py
  tests/unit/test_graph.py
Labels: enhancement
